app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    blogs = db.relationship('Blog',backref = 'user',lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Blog(db.Model):

    __tablename__ = 'blogs'

    id = db.Column(db.Integer,primary_key = True)
    # upvotes = db.Column(db.Integer)
    # downvotes = db.Column(db.Integer)
    title = db.Column(db.String)
    content = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    comments = db.relationship('Comment',backref = 'blogs',lazy = "dynamic")

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_blogs(cls):
        blogs = Blog.query.order_by(Blog.posted.desc()).all()
        return blogs

class Comment(db.Model):

    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    content = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    blog_id = db.Column(db.Integer,db.ForeignKey("blogs.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls):
        comments = Comment.query.order_by(Comment.posted.desc()).all()
        return comments
    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import Required
from wtforms import TextAreaField,SubmitField,StringField
from ..models import User

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Update bio.',validators = [Required()])
    submit = SubmitField('Update')

class PostAblog (FlaskForm):
    title = StringField('Title',validators = [Required()])
    content = TextAreaField('Start blogging',validators = [Required()])
    submit = SubmitField('Blog')

class PostAComment (FlaskForm):
    comment = TextAreaField(validators = [Required()])
    submit = SubmitField('Comment',validators = [Required()])

app/__init__.py
from flask import Flask
from flask_mail import Mail
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)



def create_app(config_name):
    
    # Initialising application
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    
    # Initialising flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    
    # Regestering the main blueprint
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/authenticate')

    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/authenticate')
    
    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from flask_login import login_required,current_user
from . import main
from .forms import UpdateProfile,PostAblog,PostAComment
from .. import db
from ..models import User,Blog,Comment
from ..requests import get_quotes

# Views
@main.route('/')
def index():

    '''
    View root page function that returns the index page and its data
    '''

    title = 'Home'
    quotes = get_quotes()

    return render_template('index.html', title = title, quotes=quotes )

@main.route('/account/<uname>',methods=['GET','POST'])
@login_required
def account(uname):

    '''
    View root page function that returns the profile page and its data
    '''

    title = 'Profile'
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort('fourOwfour')
    blogs = Blog.query.order_by(Blog.posted.desc()).all()
    
    return render_template('account.html', user = user, blogs=blogs)

@main.route('/update/<uname>',methods=['GET','POST'])
@login_required
def update(uname):

    '''
    View root page function that returns the update page and its data
    '''
    blog_form = PostAblog()
    if update_form.validate_on_submit():
        title = update_form.title.data
        blog = update_form.text.data
    
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort('fourOwfour')
    blogs = Blog.query.order_by(Blog.posted.desc()).all()
    
    return render_template('update.html', user = user, blogs=blogs)


@main.route('/blogs',methods=['GET','POST'])
def blog():
        
        form = PostAblog()
        if form.validate_on_submit():
            new_blog = Blog(title=form.title.data, content=form.content.data, user_id=current_user.id)
            new_blog.save_blog()
            return redirect(url_for('main.blog'))
        blogs= Blog.get_blogs()
        users = User.query.all()

        return render_template('blogs.html',blogs=blogs,users=users, form=form )

@main.route('/comment')
def comment():

    '''
    View root page function that returns the comments page and its data
    '''

    title = 'Comment'
    

    return render_template('comment.html', title = title )

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('update.html',uname=uname))

@main.route('/blog/new', methods=['GET', 'POST'])
@login_required
def new_blog():
    blog_form = PostAblog()
    if blog_form.validate_on_submit():
        title = blog_form.title.data
        blog = blog_form.text.data

        # Updated blog instance
        new_blog = Blog(blog_title=title, blog_content=blog, user=current_user)

        # Save blog method
        new_blog.save_blog()
        return redirect(url_for('.index'))

    title = 'New blog'
    return render_template('blogs.html', title=title)

app/templates/account.html
{% extends 'base.html' %}

<!-- Content block -->
{% block content %}

<head>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.5/css/mdb.min.css" rel="stylesheet">
    <title> {{ title }} </title>
</head>


    <div class="rare-wind-gradient" style="text-align: center">
        <div class="container">

            <h1>Profile</h1>
    
        </div>
    
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
    
        <div class="container-fluid">
            <div class="row">
                <div>
                    {% if user.profile_pic_path %}style="padding: 20px;"alt="" class="img-thumbnail" id="profpic"
                        <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" id="profpic">
                    {%else%}
                    <div class="row">
                        <div class="col-md-4">
                            {% if user.profile_pic_path %}
                                <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" id="profpic" >
                            {%else%}
                                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfZyRU5vPPm0tUo3rXKf280aJCxNZx-1OgcRrubohkf1gtrPfSYQ" alt="profile pic" class="img-thumbnail" id="profpic">
                            {% endif %}
                        </div>
                    </div>
                        <!-- <i class="fa fa-camera" id="profpic"></i> -->
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="row">
                <div class="col-md-1">
                    <a class="btn btn-lg" href="/user/{{user.username}}/update.html" role="button" >Edit Profile</a>
                </div>
        </div>
        <div class="row" id="mainprofile">
                <div class="col-md-2" id="bio">
                    {% if user %}
                        <p>@{{user.username}}</p>
                        {% if user.bio %}
                            <h5 >Bio</h6>
                            <p> {{user.bio}}</p>
                        {%else%}
                            <p> <strong>{{user.username}} has no bio</strong> </p>
                        {% endif %}
                    {% endif %}
                </div>
                <div class="col-md-6" id="myposts">
                    {% for blog in blogs %}
                        {% if blog.user_id == current_user.id %}
            <div class="row">
            <div class="col-md-2" >
                        {% if user.profile_pic_path %}
                            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail";>
                        {% endif %}
                </div>
                <div class="col-md-8">
                    <div class="row">
                        {% for user in users %}
                            {% if user.id == blog.user_id %}
                                <p>{{user.username}}</p>
                            {% endif %}
                        {% endfor %}
                        <p>{{blog.title}}</p>
                        <p>{{blog.content}}</p>
                    </div>
                    </div>
                </div>            
            </div>
            {% endif %}
            <br>
            {% endfor %}
                    <div class="row" style="padding: 10px;" >
                                
                                <a class="btn btn-primary btn-sm" href="/blogs" role="button" >Add a blog</a>
                    </div>
                </div>
            </div>
    </div>
   

{% endblock %}

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Navbar block -->
{% block navbar %}

    {% include 'navbar.html' %}
    
{% endblock %}

app/templates/blogs.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<head>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.5/css/mdb.min.css" rel="stylesheet">
    <title> {{ title }} </title>
</head>


<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">

<div class ="container" style="text-align: center; background-image: url('https://previews.123rf.com/images/maximleshkovich/maximleshkovich1702/maximleshkovich170200217/71771189-beauty-blog-background-workspace-with-laptop-gold-style-feminine-accessories-golden-tinsel-scissors-.jpg'); background-repeat : no-repeat; background-size: 100vw 100vh ; padding: 100px;">
    <div class="row" id="blogs">
        <div class="col-md-2" id="utilities">
            <div style="margin-left:40px;">
                {% for user in users %}
                {% if user.id == current_user.id %}
                {% if user.profile_pic_path %}
                <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail"
                    style="border-radius:50%; width:100px;height:100px;">
                {% endif %}
                <p style="font-weight: bold;">@{{user.username}}</p>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="col-md-6" id="myposts">
            <div class="row" style="width:100%; border-bottom: solid 1px grey;margin: 0;height:50px;">
                <div class="col-md-4">
                    <a style="color:grey;font-size: 20px;">My blogs</a>
                </div>
            </div>
            <div class="row" style="width:100%; border-bottom: solid 1px grey;margin: 0;padding-bottom: 10px;">
                <div class="col-md-8" style="margin-left:100px;">
                    {{wtf.quick_form(form)}}
                </div>
            </div>
            {% for blog in blogs %}
            <div class="row"
                style="width:100%; border-bottom: solid 1px grey;margin: 0;padding-top:10px;padding-bottom: 10px;">
                <div class="col-md-2">
                    {% for user in users %}
                    {% if user.id == blog.user_id %}
                    {% if user.profile_pic_path %}
                    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail"
                        style="border-radius:50%; width:70px;height:70px;padding:0;">
                    {% endif %}
                    {% endif %}
                    {% endfor %}
                </div>
                <div class="col-md-8">
                    <div class="row">
                        {% for user in users %}
                        {% if user.id == blog.user_id %}
                        <p style="font-weight: bold;">{{user.username}}</p>
                        {% endif %}
                        {% endfor %}
                        <p>{{blog.title}}</p>
                        <p>{{blog.content}}</p>
                    </div>
                    <div class="row">
                        <div class="col-md-2">
                            <button href='/comment' type="button" class="btn" data-toggle="modal" data-target="#myModal"
                                style="background-color: grey;color:white;font:20px;">Comment
                            </button>
                        </div>
                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog"
                            aria-labelledby="exampleModalLabel" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        {% for user in users %}
                                        {% if user.id == blog.user_id %}
                                        <h5 class="modal-title" id="exampleModalLabel" style="font-weight:bold;">
                                            @{{user.username}} (Blog: {{blog.title}})</h5>
                                        {% endif %}
                                        {% endfor %}
                                        <button type="button" class="close" data-dismiss="modal" aria-label="exit">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                        <div class="row">
                                            <div class="col-md-4">
                                                {% for user in users %}
                                                {% if user.id == current_user.id %}
                                                <p style="font-weight: bold;"> Comment by @{{user.username}}</p>
                                                {% if user.profile_pic_path %}
                                                <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt=""
                                                    class="img-thumbnail"
                                                    style="border-radius:50%; width:100px;height:100px;">
                                                {% endif %}
                                                {% endif %}
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary"
                                            data-dismiss="modal">Close</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        {% if blog.comments %}
                        <h4 style="font-weight: bold;">Comments</h4>
                        {%for comment in blog.comments %}
                        <div class="col-md-10" style="height:100px;overflow-y:scroll;">

                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

app/templates/comment.html
{% extends 'base.html' %}

<!-- Content block -->
{% block content %}

    <title> {{ title }} </title>

    <div class="container">

        <h1>Comment</h1>
        
    </div>

{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}

<!-- Content block -->
{% block content %}

<head>
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.5/css/mdb.min.css" rel="stylesheet">
    <title> {{ title }} </title>
</head>


    <div class="container rare-wind-gradient">

        <h1>This page cannot be found</h1>
        
    </div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

<!-- Content block -->
{% block content %}
    
    <head>
        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Rokkitt" rel="stylesheet">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
        <!-- Bootstrap core CSS -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.5/css/mdb.min.css" rel="stylesheet">
        <title> {{ title }} </title>
    </head>

    <div class="container" style="text-align: center; background-image: url('https://previews.123rf.com/images/neirfy/neirfy1702/neirfy170200441/73747674-feminine-workspace-with-empty-ruled-notebook-hand-writting-in-it-coffee-flowers-and-laptop-keyboard.jpg'); background-repeat : no-repeat; background-size: 100vw 100vh ; padding: 100px;">
    <!--Header-->
    <div class="row d-flex justify-content-center" >
        <h1 class="black-text mb-3 pt-3 font-weight-bold">WELCOME TO CODE BLOG</h1>
    </div>

    <div class="row mt-2 mb-3 d-flex justify-content-center" style="background-color:rgba(201, 196, 196, 0.603);">
        <div class="" style="font-size: 20px; margin-top:40px">
            {{ quotes.quote }}
            <cite title="Source Title"> {{ quotes.author }} </cite>
        </div>


    </div>
    </div>


     <!-- JQuery -->
     <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
     <!-- Bootstrap tooltips -->
     <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
     <!-- Bootstrap core JavaScript -->
     <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
     <!-- MDB core JavaScript -->
     <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.7.6/js/mdb.min.js"></script>

{% endblock %}

app/templates/navbar.html
{% extends 'base.html' %}

<!-- Navbar block -->
{% block navbar %}
    <div class="container-fluid ">

        <div class="navbar navbar-expand-lg tempting-azure-gradient" role="navigation" >

            <div class="container">

                <div class="navbar-header">

                    <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">

                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>

                    </button>


                </div>

                <div class="navbar-collapse collapse">

                    <ul  class="nav navbar-nav">

                        <li>
                            <a style="color: black" href="/">Home</a>
                        </li>
                        <li>
                            <a style="color: black" href="/blogs">Blogs</a>
                        </li>
                        
                        {% if current_user.is_authenticated %}
                        <li>
                            <a style="color: black" href="{{url_for('main.account',uname=current_user.username)}}">Account</a>
                        </li>
                        <li>
                            <a style="color: black" href="{{url_for('auth.logout')}}">Log out</a>
                        </li>
                        {% else %}
                        <li>
                            <a style="color: black" href="{{url_for('auth.login')}}">Log in</a>
                        </li>
                        {%endif%}
                    </ul>

                </div>

            </div>

        </div>

    </div>
{% endblock %}

app/templates/update.html
{% extends 'base.html' %}

<!-- Content block -->
{% block content %}

    <title> {{ title }} </title>

    <div class="container">

        <h1>update</h1>

    </div>

{% endblock %}